//
//  File.swift
//  
//
//  Created by Roman Dzieciol on 7/3/19.
//

import SwiftSyntax

// Collections

extension AccessPathSyntax: ItemOrArray {}
extension AccessorListSyntax: ItemOrArray {}
extension ArrayElementListSyntax: ItemOrArray {}
extension AttributeListSyntax: ItemOrArray {}
extension AvailabilitySpecListSyntax: ItemOrArray {}
extension CaseItemListSyntax: ItemOrArray {}
extension CatchClauseListSyntax: ItemOrArray {}
extension ClosureCaptureItemListSyntax: ItemOrArray {}
extension ClosureParamListSyntax: ItemOrArray {}
extension CodeBlockItemListSyntax: ItemOrArray {}
extension CompositionTypeElementListSyntax: ItemOrArray {}
extension ConditionElementListSyntax: ItemOrArray {}
extension DeclNameArgumentListSyntax: ItemOrArray {}
extension DictionaryElementListSyntax: ItemOrArray {}
extension EnumCaseElementListSyntax: ItemOrArray {}
extension ExprListSyntax: ItemOrArray {}
extension FunctionCallArgumentListSyntax: ItemOrArray {}
extension FunctionParameterListSyntax: ItemOrArray {}
extension GenericArgumentListSyntax: ItemOrArray {}
extension GenericParameterListSyntax: ItemOrArray {}
extension GenericRequirementListSyntax: ItemOrArray {}
extension IdentifierListSyntax: ItemOrArray {}
extension IfConfigClauseListSyntax: ItemOrArray {}
extension InheritedTypeListSyntax: ItemOrArray {}
extension MemberDeclListSyntax: ItemOrArray {}
extension ModifierListSyntax: ItemOrArray {}
extension NonEmptyTokenListSyntax: ItemOrArray {}
extension ObjCSelectorSyntax: ItemOrArray {}
extension ObjcNameSyntax: ItemOrArray {}
extension PatternBindingListSyntax: ItemOrArray {}
extension PrecedenceGroupAttributeListSyntax: ItemOrArray {}
extension PrecedenceGroupNameListSyntax: ItemOrArray {}
extension SpecializeAttributeSpecListSyntax: ItemOrArray {}
extension StringInterpolationSegmentsSyntax: ItemOrArray {}
extension SwitchCaseListSyntax: ItemOrArray {}
extension TokenListSyntax: ItemOrArray {}
extension TupleElementListSyntax: ItemOrArray {}
extension TuplePatternElementListSyntax: ItemOrArray {}
extension TupleTypeElementListSyntax: ItemOrArray {}

// Nodes

extension AccessLevelModifierSyntax: ItemOrArray {}
extension AccessPathComponentSyntax: ItemOrArray {}
extension AccessorBlockSyntax: ItemOrArray {}
extension AccessorDeclSyntax: ItemOrArray {}
extension AccessorParameterSyntax: ItemOrArray {}
extension ArrayElementSyntax: ItemOrArray {}
extension ArrayExprSyntax: ItemOrArray {}
extension ArrayTypeSyntax: ItemOrArray {}
extension ArrowExprSyntax: ItemOrArray {}
extension AsExprSyntax: ItemOrArray {}
extension AsTypePatternSyntax: ItemOrArray {}
extension AssignmentExprSyntax: ItemOrArray {}
extension AssociatedtypeDeclSyntax: ItemOrArray {}
extension AttributeSyntax: ItemOrArray {}
extension AttributedTypeSyntax: ItemOrArray {}
extension AvailabilityArgumentSyntax: ItemOrArray {}
extension AvailabilityConditionSyntax: ItemOrArray {}
extension AvailabilityLabeledArgumentSyntax: ItemOrArray {}
extension AvailabilityVersionRestrictionSyntax: ItemOrArray {}
extension BinaryOperatorExprSyntax: ItemOrArray {}
extension BooleanLiteralExprSyntax: ItemOrArray {}
extension BreakStmtSyntax: ItemOrArray {}
extension CaseItemSyntax: ItemOrArray {}
extension CatchClauseSyntax: ItemOrArray {}
extension ClassDeclSyntax: ItemOrArray {}
extension ClassRestrictionTypeSyntax: ItemOrArray {}
extension ClosureCaptureItemSyntax: ItemOrArray {}
extension ClosureCaptureSignatureSyntax: ItemOrArray {}
extension ClosureExprSyntax: ItemOrArray {}
extension ClosureParamSyntax: ItemOrArray {}
extension ClosureSignatureSyntax: ItemOrArray {}
extension CodeBlockItemSyntax: ItemOrArray {}
extension CodeBlockSyntax: ItemOrArray {}
extension CompositionTypeElementSyntax: ItemOrArray {}
extension CompositionTypeSyntax: ItemOrArray {}
extension ConditionElementSyntax: ItemOrArray {}
extension ConformanceRequirementSyntax: ItemOrArray {}
extension ContinueStmtSyntax: ItemOrArray {}
extension DeclModifierSyntax: ItemOrArray {}
extension DeclNameArgumentSyntax: ItemOrArray {}
extension DeclNameArgumentsSyntax: ItemOrArray {}
extension DeclNameSyntax: ItemOrArray {}
extension DeclarationStmtSyntax: ItemOrArray {}
extension DeferStmtSyntax: ItemOrArray {}
extension DeinitializerDeclSyntax: ItemOrArray {}
extension DictionaryElementSyntax: ItemOrArray {}
extension DictionaryExprSyntax: ItemOrArray {}
extension DictionaryTypeSyntax: ItemOrArray {}
extension DiscardAssignmentExprSyntax: ItemOrArray {}
extension DoStmtSyntax: ItemOrArray {}
extension DotSelfExprSyntax: ItemOrArray {}
extension EditorPlaceholderExprSyntax: ItemOrArray {}
extension ElseBlockSyntax: ItemOrArray {}
extension ElseIfContinuationSyntax: ItemOrArray {}
extension EnumCaseDeclSyntax: ItemOrArray {}
extension EnumCaseElementSyntax: ItemOrArray {}
extension EnumCasePatternSyntax: ItemOrArray {}
extension EnumDeclSyntax: ItemOrArray {}
extension ExpressionPatternSyntax: ItemOrArray {}
extension ExpressionSegmentSyntax: ItemOrArray {}
extension ExpressionStmtSyntax: ItemOrArray {}
extension ExtensionDeclSyntax: ItemOrArray {}
extension FallthroughStmtSyntax: ItemOrArray {}
extension FloatLiteralExprSyntax: ItemOrArray {}
extension ForInStmtSyntax: ItemOrArray {}
extension ForcedValueExprSyntax: ItemOrArray {}
extension FunctionCallArgumentSyntax: ItemOrArray {}
extension FunctionCallExprSyntax: ItemOrArray {}
extension FunctionDeclSyntax: ItemOrArray {}
extension FunctionParameterSyntax: ItemOrArray {}
extension FunctionSignatureSyntax: ItemOrArray {}
extension FunctionTypeSyntax: ItemOrArray {}
extension GenericArgumentClauseSyntax: ItemOrArray {}
extension GenericArgumentSyntax: ItemOrArray {}
extension GenericParameterClauseSyntax: ItemOrArray {}
extension GenericParameterSyntax: ItemOrArray {}
extension GenericWhereClauseSyntax: ItemOrArray {}
extension GuardStmtSyntax: ItemOrArray {}
extension IdentifierExprSyntax: ItemOrArray {}
extension IdentifierPatternSyntax: ItemOrArray {}
extension IfConfigClauseSyntax: ItemOrArray {}
extension IfConfigDeclSyntax: ItemOrArray {}
extension IfStmtSyntax: ItemOrArray {}
extension ImplementsAttributeArgumentsSyntax: ItemOrArray {}
extension ImplicitMemberExprSyntax: ItemOrArray {}
extension ImplicitlyUnwrappedOptionalTypeSyntax: ItemOrArray {}
extension ImportDeclSyntax: ItemOrArray {}
extension InOutExprSyntax: ItemOrArray {}
extension InheritedTypeSyntax: ItemOrArray {}
extension InitializerClauseSyntax: ItemOrArray {}
extension InitializerDeclSyntax: ItemOrArray {}
extension IntegerLiteralExprSyntax: ItemOrArray {}
extension IsExprSyntax: ItemOrArray {}
extension IsTypePatternSyntax: ItemOrArray {}
extension KeyPathBaseExprSyntax: ItemOrArray {}
extension KeyPathExprSyntax: ItemOrArray {}
extension LabeledSpecializeEntrySyntax: ItemOrArray {}
extension MatchingPatternConditionSyntax: ItemOrArray {}
extension MemberAccessExprSyntax: ItemOrArray {}
extension MemberDeclBlockSyntax: ItemOrArray {}
extension MemberDeclListItemSyntax: ItemOrArray {}
extension MemberTypeIdentifierSyntax: ItemOrArray {}
extension MetatypeTypeSyntax: ItemOrArray {}
extension NamedAttributeStringArgumentSyntax: ItemOrArray {}
extension NilLiteralExprSyntax: ItemOrArray {}
extension ObjCSelectorPieceSyntax: ItemOrArray {}
extension ObjcKeyPathExprSyntax: ItemOrArray {}
extension ObjcNamePieceSyntax: ItemOrArray {}
extension ObjcSelectorExprSyntax: ItemOrArray {}
extension ObjectLiteralExprSyntax: ItemOrArray {}
extension OperatorDeclSyntax: ItemOrArray {}
extension OperatorPrecedenceAndTypesSyntax: ItemOrArray {}
extension OptionalBindingConditionSyntax: ItemOrArray {}
extension OptionalChainingExprSyntax: ItemOrArray {}
extension OptionalPatternSyntax: ItemOrArray {}
extension OptionalTypeSyntax: ItemOrArray {}
extension ParameterClauseSyntax: ItemOrArray {}
extension PatternBindingSyntax: ItemOrArray {}
extension PostfixUnaryExprSyntax: ItemOrArray {}
extension PoundAssertStmtSyntax: ItemOrArray {}
extension PoundColumnExprSyntax: ItemOrArray {}
extension PoundDsohandleExprSyntax: ItemOrArray {}
extension PoundErrorDeclSyntax: ItemOrArray {}
extension PoundFileExprSyntax: ItemOrArray {}
extension PoundFunctionExprSyntax: ItemOrArray {}
extension PoundLineExprSyntax: ItemOrArray {}
extension PoundSourceLocationArgsSyntax: ItemOrArray {}
extension PoundSourceLocationSyntax: ItemOrArray {}
extension PoundWarningDeclSyntax: ItemOrArray {}
extension PrecedenceGroupAssignmentSyntax: ItemOrArray {}
extension PrecedenceGroupAssociativitySyntax: ItemOrArray {}
extension PrecedenceGroupDeclSyntax: ItemOrArray {}
extension PrecedenceGroupNameElementSyntax: ItemOrArray {}
extension PrecedenceGroupRelationSyntax: ItemOrArray {}
extension PrefixOperatorExprSyntax: ItemOrArray {}
extension ProtocolDeclSyntax: ItemOrArray {}
extension RepeatWhileStmtSyntax: ItemOrArray {}
extension ReturnClauseSyntax: ItemOrArray {}
extension ReturnStmtSyntax: ItemOrArray {}
extension SameTypeRequirementSyntax: ItemOrArray {}
extension SequenceExprSyntax: ItemOrArray {}
extension SimpleTypeIdentifierSyntax: ItemOrArray {}
extension SourceFileSyntax: ItemOrArray {}
extension SpecializeExprSyntax: ItemOrArray {}
extension StringInterpolationExprSyntax: ItemOrArray {}
extension StringLiteralExprSyntax: ItemOrArray {}
extension StringSegmentSyntax: ItemOrArray {}
extension StructDeclSyntax: ItemOrArray {}
extension SubscriptDeclSyntax: ItemOrArray {}
extension SubscriptExprSyntax: ItemOrArray {}
extension SuperRefExprSyntax: ItemOrArray {}
extension SwitchCaseLabelSyntax: ItemOrArray {}
extension SwitchCaseSyntax: ItemOrArray {}
extension SwitchDefaultLabelSyntax: ItemOrArray {}
extension SwitchStmtSyntax: ItemOrArray {}
extension SymbolicReferenceExprSyntax: ItemOrArray {}
extension TernaryExprSyntax: ItemOrArray {}
extension ThrowStmtSyntax: ItemOrArray {}
extension TryExprSyntax: ItemOrArray {}
extension TupleElementSyntax: ItemOrArray {}
extension TupleExprSyntax: ItemOrArray {}
extension TuplePatternElementSyntax: ItemOrArray {}
extension TuplePatternSyntax: ItemOrArray {}
extension TupleTypeElementSyntax: ItemOrArray {}
extension TupleTypeSyntax: ItemOrArray {}
extension TypeAnnotationSyntax: ItemOrArray {}
extension TypeExprSyntax: ItemOrArray {}
extension TypeInheritanceClauseSyntax: ItemOrArray {}
extension TypeInitializerClauseSyntax: ItemOrArray {}
extension TypealiasDeclSyntax: ItemOrArray {}
extension UnknownDeclSyntax: ItemOrArray {}
extension UnknownExprSyntax: ItemOrArray {}
extension UnknownPatternSyntax: ItemOrArray {}
extension UnknownStmtSyntax: ItemOrArray {}
extension UnknownSyntax: ItemOrArray {}
extension UnknownTypeSyntax: ItemOrArray {}
extension UnresolvedPatternExprSyntax: ItemOrArray {}
extension ValueBindingPatternSyntax: ItemOrArray {}
extension VariableDeclSyntax: ItemOrArray {}
extension VersionTupleSyntax: ItemOrArray {}
extension WhereClauseSyntax: ItemOrArray {}
extension WhileStmtSyntax: ItemOrArray {}
extension WildcardPatternSyntax: ItemOrArray {}
extension YieldListSyntax: ItemOrArray {}
extension YieldStmtSyntax: ItemOrArray {}

extension TokenSyntax: ItemOrArray {}
